::1 - - [15/Nov/2024 06:19:27] "GET /templates/login.html HTTP/1.1" 200 -
::1 - - [15/Nov/2024 06:19:27] "GET /static/css/style.css HTTP/1.1" 200 -
::1 - - [15/Nov/2024 06:19:27] "GET /static/js/auth.js HTTP/1.1" 200 -
::1 - - [15/Nov/2024 06:19:27] code 404, message File not found
::1 - - [15/Nov/2024 06:19:27] "GET /favicon.ico HTTP/1.1" 404 -
works/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 1261, in test
    with ServerClass(addr, HandlerClass) as httpd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 457, in __init__
    self.server_bind()
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 1308, in server_bind
    return super().server_bind()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/server.py", line 136, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/opt/homebrew/Cellar/python@3.12/3.12.5/Frameworks/Python.framework/Versions/3.12/lib/python3.12/socketserver.py", line 473, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 48] Address already in use
